### ISSUE TITLE
No ReadMe

### ISSUE THREAD

**Issue by HudsonLanier** [Murithijoshua/Rest_like_A_boss#3]
Hello, 

The ReadMe.md file for this is blank. When I cloned your code in PyCharm and ran it, nothing happened. A ReadMe file with instructions about how to install and run the program would be very helpful for this reason.

**Comment by Murithijoshua** [comment]
HI,👋
I have updated the readme.md, all instructions have been added. incase you of inconviniences lemme know.
thanks.
